#!/bin/bash
# Copyright 2019, John Unland (Forked)
# Copyright 2018, Emmett1  (emmett1.2miligrams@gmail.com)
# SPDX-License-Identifier: GPL-3.0-or-later

name=${1:-foo}
version=${2:-0.1}
release=${3:-1}
outputdir=${4:-/tmp}
target=${5:-PWD}
tar -cvJpf $outputdir/$name-$version-$release.spkg.txz *
