#!/bin/bash
# Copyright 2019, John Unland (Forked)
# Copyright 2018, Emmett1  (emmett1.2miligrams@gmail.com)
# SPDX-License-Identifier: GPL-3.0-or-later

if [ -d $1 ]; then
	echo "ERROR: Directory '$1' already exist!"
	exit 1
else
	mkdir $1
	echo "# description	: 
# homepage	: 
# depends	: 

name=$1
version=
release=1
options=()
noextract=()
backup=()
source=()
md5sum=()

build() {
	cd \$name-\$version
	./configure --prefix=/usr
	make
	make DESTDIR=\$PKG install
}" > $1/spkgbuild
	echo "Template port have created for '$1'."
fi

exit 0
