#!/bin/bash
# Copyright 2019, John Unland (Forked)
# Copyright 2018, Emmett1  (emmett1.2miligrams@gmail.com)
# SPDX-License-Identifier: GPL-3.0-or-later

if [ "$UID" != 0 ]; then
	echo "This operation need root access. Exiting..."
	exit 1
fi

spkgnew=$(find /etc -regextype posix-extended -regex ".+\.spkgnew" 2> /dev/null)

if [ -z "$spkgnew" ]; then
	echo "Nothing to do. Exiting..."
	exit 0
fi

for file in $spkgnew; do
	clear
	currentfile=${file%.*}
	if [ ! -e "$currentfile" ]; then
		echo "Remove '$file', '$currentfile' not exist."
		rm -f "$file"
		sleep 1
		continue
	fi
	diff -u $currentfile $file --color=always
	if [ $? = 0 ]; then
		echo "Remove '$file', no diff found."
		rm -f "$file"
		sleep 1
		continue
	fi
	echo
	echo "Choose action:"
	echo "1) Keep original"
	echo "2) Replace original with new"
	echo "*) Do nothing"
	echo
	echo -n "Action: "
	read ACTION
	if [ "$ACTION" = "1" ]; then
		echo "Remove '$file'"
		rm -f "$file"
	elif [ "$ACTION" = "2" ]; then
		echo "Replace '$currentfile' with '$file'."
		mv "$file" "$currentfile"
	else
		echo "Doing nothing."
	fi
	sleep 1
done

clear

echo "Done updating package's configuration files."

exit 0
